name: Package release with PyInstaller

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'

env:
  EXECUTABLE_NAME: "homologations_suggester"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3
        with:
          version: "0.7.4"
          python-version: "3.13"
      - name: Compile executable
        run: uv run pyinstaller --name="${{ env.EXECUTABLE_NAME }}" --onefile ./src/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-x86_64-artifact
          path: dist/${{ env.EXECUTABLE_NAME }}.exe
          overwrite: true
          archive: false
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3
        with:
          version: "0.7.4"
          python-version: "3.13"
      - name: Compile executable
        run: uv run pyinstaller --name="${{ env.EXECUTABLE_NAME }}" --onefile ./src/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-x86_64-artifact
          path: dist/${{ env.EXECUTABLE_NAME }}
          overwrite: true
          archive: false
  upload-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Archive windows release
        uses: montudor/action-zip@v1
        with:
          args: zip homologations-suggester-x86_64-windows.zip etc/usr/artifacts/windows-x86_64-artifact/${{ env.EXECUTABLE_NAME }}.exe transition_plan.db template.xlsx
      - name: Archive linux release
        uses: montudor/action-zip@v1
        with:
          args: zip homologations-suggester-x86_64-linux.zip etc/usr/artifacts/linux-x86_64-artifact/${{ env.EXECUTABLE_NAME }} transition_plan.db template.xlsx
